services:
  nginx:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - network
    depends_on:
      - project1
      - project2
      - websocket
      

  project1:
    build:
      context: .
      dockerfile: docker/project1/Dockerfile
    container_name: project1
    volumes:
      - ./src/project1:/var/www/html
    networks:
      - network

  project2:
    build:
      context: .
      dockerfile: docker/project2/Dockerfile
    container_name: project2
    volumes:
      - ./src/project2:/var/www/html
    networks:
      - network

  websocket:
    build:
      context: .
      dockerfile: docker/websocket/Dockerfile
    container_name: websocket-server
    ports:
      - "3000:3000"
    networks:
      - network

networks:
  network:
    driver: bridge
